version: '2'
services:
  front:
    image: node:carbon
    command: yarn start
    working_dir: /srv
    volumes:
      - ./front-end:/srv:Z
    ports:
      - 3000:3000
  back:
    image: node:carbon
    command: yarn start
    working_dir: /srv
    volumes:
      - ./back-end:/srv:Z
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development